### ISSUE TITLE
update to 10.1.37

### ISSUE THREAD

**Issue by prwhitaker** [iuscommunity-pkg/mariadb101u#12]
Hi

The current available version of MariaDB 10.1 in IUS is 10.1.35, however upstream MariaDB is now up to 10.1.37: https://mariadb.org/mariadb-10-1-37-now-available/

There is at least one problematic issue we've seen in 10.1.35 where it doesn't always clean up temporary tables from disk https://jira.mariadb.org/browse/MDEV-16647 which was marked as fixed in 10.1.36: https://mariadb.com/kb/en/library/mariadb-10136-changelog/

Could we please get the latest version available when you get a chance?

Thanks

**Comment by carlwgeorge** [comment]
@smokris Any interest in helping out with this one?

**Comment by carlwgeorge** [comment]
This package has been updated to 10.1.40 and is currently available from ius-testing.  I'll move it to stable in about a week.
