### ISSUE TITLE
mysql_upgrade moved to mariadb101u-server-utils in 10.1.24

### ISSUE THREAD

**Issue by mikegriffin** [iuscommunity-pkg/mariadb101u#6]
While some of the binaries in mariadb101u-server-utils are "non-essential", I would think that mysql_upgrade should ship with the mariadb101u-server, since it is required during major upgrades (eg from mariadb10u-server to mariadb101u-server)

Please consider including mysql_upgrade with the server again in your next release.

**Comment by b-harper** [comment]
Hey @mikegriffin,

Thanks for taking the time to submit this issue and chat about it over IRC.  Here is the [commit][0] where Fedora made this change.  EL7 stock mariadb packages have the mysql_upgrade file apart of the mariadb-server package.  While we tend to align with Fedora as much as possible, this might be a situation where it makes sense to align with EL7.  I am curious if other have thoughts about where the mysql_upgrade file should live.

Seeing that MariaDB releases new versions roughly once a month, I think we can hold off till the next version if we choose to make any changes.

[0]: http://pkgs.fedoraproject.org/cgit/rpms/mariadb.git/commit/?id=ae4f65b4613485556cbb2056e7f20544ca811958

**Comment by mikegriffin** [comment]
Ben,
If it is documented and easily discoverable for users to find mysql_upgrade in -server-utils then feel free to close this. I was just surprised when upgrading from 10.0 to 10.1 and unable to run mysql_upgrade until I downgraded to 10.1.23 to use mysql_upgrade, and then back to 10.1.24. I did not need mysql_upgrade again in 10.1.24 since this was a minor version change x.x.23 to x.x.24

Normally, mysql_upgrade is shipped with the server because, in the case of a major version change x.0.x to x.1.x there will often be changes to table definitions in the `mysql` database (different columns).

**Comment by xarr** [comment]
+1: In favor of moving mysql_upgrade back to '-server', in alignment with EL7.

**Comment by b-harper** [comment]
@mikegriffin,

There are a few different ways a user could discover this change.  A user could run ```yum whatprovides mysql_upgrade``` to show which packages include mysql_upgrade.  The rpm changelog and/or the git commit history could also be used.  That being said, I am not sure any of these options could be described as 'easily discoverable'.

In regards to why Fedora made this change, I could speculate that minimum containers could be a factor.   Also, Fedora has [weak dependencies][0] which are not in EL yet.

@xarr, thanks for the feedback here and over IRC.  

[0]: http://rpm.org/user_doc/dependencies.html#weak-dependencies

**Comment by carlwgeorge** [comment]
Are any of the other utilities considered important enough to move back to the -server subpackage?

* `mysql_convert_table_format`
* `mysql_fix_extensions`
* `mysql_setpermission`
* `mysql_zap`
* `mysqldumpslow`
* `mysqld_multi`
* `mysqlhotcopy`
* `mysqltest`
* `perror`
* `mysqld_safe_helper`

**Comment by mikegriffin** [comment]
`perror` is pretty useful but not "important enough" to be considered a defect. The other stuff is probably pretty rarely used.

**Comment by mikegriffin** [comment]
Sorry, `perror`, if shipped (not required really), would live with -client IIRC. It is fine in -server-utils IHMO.

**Comment by b-harper** [comment]
We will proceed with moving just mysql_upgrade in the new [10.1.25 release][0].


[0]: https://mariadb.com/kb/en/mariadb/mariadb-10125-release-notes/
