### ISSUE TITLE
mysqld_safe_helper moved to mariadb101u-server-utils in 10.1.24

### ISSUE THREAD

**Issue by prwhitaker** [iuscommunity-pkg/mariadb101u#8]
This was already noted in passing under issue #6 - the `mysqld_safe_helper` script was moved to the mariadb101u-server-utils package in version 10.1.24 (commit 58dd40b42de2fbe71f55a29406e6ccc84b41622c)

However, the `mysqld_safe` script is still in the mariadb101u-server package, and it relies on `mysqld_safe_helper` being present - these two scripts really ought to be in the same package.

This isn't normally a problem on RHEL7/CentOS 7, as the systemd unit runs the mysqld binary directly - however the mysql resource in Pacemaker (RHEL 7 clustering) defaults to running the `mysqld_safe` script, which then fails due to the lack of `mysqld_safe_helper` if the server-utils package isn't present

**Comment by b-harper** [comment]
Hey @prwhitaker,

Thanks for taking the time to submit this issue.  As stated in #6, we moved non-essential scripts to a separate package to align with Fedora.  Then we moved ```mysql_upgrade``` back as it seemed to be part of the core experience of using MariaDB.  It is my view that Pacemaker is not part of the core experience and I do not think it is unreasonable to install an additional package.  That being said, I am not DBA. If there are compelling reason why ```mysqld_safe_helper``` should be moved out of mariadb101u-server-utils, please let us know.

**Comment by prwhitaker** [comment]
I don't think it matters particularly which package the script is in - just that as `mysqld_safe` requires `mysqld_safe_helper`, those two scripts ought to be in the same package rather than separate ones

**Comment by carlwgeorge** [comment]
I completely agree @prwhitaker.  I just moved `mysqld_safe_helper` back to the server subpackage.  The builds are in progress and they should be published to our testing repositories during tonight's automation.

**Comment by b-harper** [comment]
Seeing that MariaDB 10.1.26 just got released, we will roll this changed into that release.  The mariadb101u-10.1.26-1 packages will be hitting the testing repositories during tonight's automation.
